### ISSUE TITLE
Is it possible to build a Portein-RNA-binding motif database such as CISBP-RNA and import into MotifDb? 

### ISSUE THREAD

**Issue by hongjianjin** [PriceLab/MotifDb#7]

**Comment by paul-shannon** [comment]
@hongjianjin 

I have retired from the ISB, and from bioinformatics.  Geo Vogler offered to take over the package.  It is now (and for many years past) maintained via Bioconductor.  So your best bet is to ask the question on the Bioconductor support site.  See https://bioconductor.org/packages/release/bioc/html/MotifDb.html and the button which reads  "Need some help?"

I hope this proves helpful.

 - Paul
